### ISSUE TITLE
[rust] Implement new concept exercise: turbofish

### ISSUE THREAD

**Issue by coriolinus** [iHiD/v3#32]
This issue describes how to implement the [`turbofish`](https://turbo.fish/) concept exercise for the rust track.

## Goal

Rust offers the `::<_>` operator, popularly known as the turbofish. AFAIK no other language has this operator, which is used for offering hints to the type inferencer where it would otherwise fail.

In v2, we have shoehorned some instruction about this operator into the `reverse-string` exercise, but this comes with a drawback: it implies that people should use the manual operator even when the code is simpler and clearer without it. 

## Things to teach

- existence of turbofish operator
- when and how to use turbofish operator

## Things not to teach

- turbofish should be used unconditionally
- partial type hints i.e. `collect::<Result<Vec<_>, _>>()`

## Concepts

- turbofish

## Prequisites

- generics

## Implementing

A sketch of an exercise implementation exists [on the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=238cae4540ae3e634efd6964e6917d21)

## Help

If you have any questions while implementing the exercise, please post the questions as comments in this issue.

**Comment by coriolinus** [comment]
I _just_ noticed I created this issue in the wrong repo. @iHiD, will you move this issue to the `exercism` repo, please?

**Comment by iHiD** [comment]
I can't move across repos, sorry. You'll need to copy+paste it there.
